image: composer:latest

before_script: [composer install]

test:pspec:
  script: src/bin/pspec spec

test:examples:
  script: src/bin/pspec examples

lint:
  before_script:
    - cd tools/php-cs-fixer
    - composer install
    - cd ../..
  script:
    - tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --dry-run --diff
