image: composer:latest

before_script: [composer install]

test:pspec:
  before_script:
    - apk add autoconf build-base
    - pecl install xdebug
    - echo 'zend_extension=xdebug' >> /usr/local/etc/php/php-cli.ini
    - echo 'memory_limit = 256M' >> /usr/local/etc/php/php-cli.ini
    - composer install
  script: XDEBUG_MODE=coverage src/bin/pspec spec
  artifacts:
    reports:
      junit: junit.xml

test:examples:
  script: src/bin/pspec examples

lint:
  before_script:
    - cd tools/php-cs-fixer
    - composer install
    - cd ../..
  script:
    - tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --dry-run --diff

pages:
  image: ubuntu:latest
  before_script:
    - apt-get update
    - apt-get install wget -y
    - wget https://github.com/Doctave/doctave/releases/download/0.4.2/doctave-0.4.2-x86_64-unknown-linux-musl.tar.gz
    - tar xvf doctave*.tar.gz
    - rm doctave*.tar.gz
    - mv doctave*/doctave /bin
  script:
    - doctave build --release --allow-failed-checks
    - mv site public
  environment:
    name: docs
    url: https://codingpaws.gitlab.io/pspec
  artifacts:
    paths:
      - public
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
